version: 2.1

orbs:
  go: circleci/go@1.7.3

jobs:
  lint-dockerfile:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            docker run --rm --interactive hadolint/hadolint < Dockerfile
  build-app-karsajobs:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t ghcr.io/sayed-k-ali/karsajobs-ui:latest .
      - run:
          name: Login to container registry
          command: docker login ghcr.io -u sayed-k-ali -p ${GHCR_TOKEN}
      - run:
          name: Push docker image to container registry
          command: docker push ghcr.io/sayed-k-ali/karsajobs-ui:latest

workflows:
  ci:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs:
          requires:
            - lint-dockerfile

